# Generated by Django 3.1.2 on 2020-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelstuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
